# Generated by Django 4.2.6 on 2026-05-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_projectsection_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsection",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="home.servicesection"
            ),
        ),
    ]
