# Generated by Django 4.2.6 on 2026-05-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_projectsection_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsection",
            name="services",
        ),
        migrations.AddField(
            model_name="servicesection",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="home.projectsection",
            ),
        ),
    ]
