# Generated by Django 4.2.6 on 2026-05-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0019_service_fk_to_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsection",
            name="client",
        ),
        migrations.RemoveField(
            model_name="projectsection",
            name="company",
        ),
        migrations.RemoveField(
            model_name="projectsection",
            name="duration",
        ),
    ]
